Name:           ros-melodic-automotive-autonomy-msgs
Version:        3.0.1
Release:        1%{?dist}
Summary:        ROS automotive_autonomy_msgs package

Group:          Development/Libraries
License:        MIT
URL:            http://github.com/automotive_autonomy_msgs
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-automotive-navigation-msgs
Requires:       ros-melodic-automotive-platform-msgs
BuildRequires:  ros-melodic-catkin

%description
Messages for vehicle automation

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Dec 12 2019 AutonomouStuff Software Development Team <software@autonomoustuff.com> - 3.0.1-1
- Autogenerated by Bloom

* Fri Dec 07 2018 AutonomouStuff Software Development Team <software@autonomoustuff.com> - 2.0.3-0
- Autogenerated by Bloom

* Wed Aug 08 2018 AutonomouStuff Software Development Team <software@autonomoustuff.com> - 2.0.2-0
- Autogenerated by Bloom

